version: '2.2'
services:
  eventsdb:
    image: postgres:9.6
    container_name: eventsdb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /opt/srv-events-db:/docker-entrypoint-initdb.d
  vh-srv-events:
    container_name: 'vh-srv-events'
    environment: 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: "${DB_HOST}"
      PGPORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_APPNAME: "bbdev"
      APP_PORT: "${APP_PORT}"
      APP_MODE: "${APP_MODE}"
    image: "${IMAGE_NAME}"
    cpus: '0.5'
    mem_limit: 250M
    ports:
      - 7475:8080
networks:
    default:
        external:
            name: vh
